version: '3'
services:
  athina-web:
    image: test #athinaedu/athina-web:latest
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --bind :8000 athinaweb.wsgi:application"
    volumes:
      - ./static_files/:/code/static_files/
    ports:
      - "8000:8000"
